name: Push package to nexus APT repo

on:
  push:
    branches:
      - main

env:
  REPO_USER: ${{ secrets.NEXUS_USER }}
  REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  REPO_URL: https://nexus.mekomsolutions.net/repository/mks-apt/
  DEBEMAIL: support@mekomsolutions.com
  DEBFULLNAME: Mekom Solutions

jobs:
  push-deb:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Update apt repositories
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -qq -y curl dh-make devscripts build-essential dh-systemd

      - name: Build usb-autorunner-dev
        working-directory: ./usb-autorunner-dev
        run: debuild -us -uc

      - name: Build usb-autorunner
        working-directory: ./usb-autorunner
        run: debuild -us -uc

      - name: Build usb-autorunner-profiles
        working-directory: ./usb-autorunner-profiles
        run: debuild -us -uc

      - name: Push usb-autorunner package to Apt repository
        run: "curl -u \"$REPO_USER:$REPO_PASSWORD\" -H \"Content-Type: multipart/form-data\" --data-binary \"@./usb-autorunner_0.1-1_all.deb\" \"$REPO_URL\""

      - name: Push usb-autorunner-dev package to Apt repository
        run: "curl -u \"$REPO_USER:$REPO_PASSWORD\" -H \"Content-Type: multipart/form-data\" --data-binary \"@./usb-autorunner-dev_0.1-1_all.deb\" \"$REPO_URL\""

      - name: Push usb-autorunner-dev package to Apt repository
        run: "curl -u \"$REPO_USER:$REPO_PASSWORD\" -H \"Content-Type: multipart/form-data\" --data-binary \"@./usb-autorunner-profiles_0.1-1_all.deb\" \"$REPO_URL\""
